### ISSUE TITLE
Location - Suggestion

### ISSUE THREAD

**Issue by evernife** [KaiKikuchi/BetterChunkLoader#11]
It would be good to have a location lang file in the config folder :/

**Comment by DarkBlade177** [comment]
> {
> 	player.sendMessage(ChatColor.GOLD + "Iron and Diamond blocks can be converted into chunk loaders. Right click it with a blaze rod.");
> }

I dont know how to programing, so, if i change this messages using normal color codes

> &1&2  &l

Will it work?

**Comment by KaiKikuchi** [comment]
No, it will not work. If you're not a developer, I strongly suggest you to wait for the next update that will support messages customization.

**Comment by KaiKikuchi** [comment]
Added on v.2.5
