### ISSUE TITLE
Chunk Block - Suggestion

### ISSUE THREAD

**Issue by evernife** [KaiKikuchi/BetterChunkLoader#12]
A way to change the default ChunkLoader-Blocks do another ones.

**Comment by KaiKikuchi** [comment]
Added on v.2.5

**Comment by evernife** [comment]
Sorry, i had not tested it yet cause i was still building my mod...

(Here is my chunk loader :V
![image](https://cloud.githubusercontent.com/assets/11357801/20420565/cbb2888c-ad45-11e6-8767-cd0470ac5883.png)
)

Now that i have it i was trying to see up its ID but it did nor work :/

I tried, for exemple the item ids :

```
OnlineOnlyBlockMaterial: 1614:2 
AlwaysOnBlockMaterial: 1614:2
```
dir not work, then i tried vanilla items like CLAY or STONE;

None of them worked too,   : /

To be sure, i tried to just invert the two blocks. Same problem, did nor work...


And just to point out, I get this error when reloading the plugin (whatever it was set in the config)

```
[01:09:52] [Server thread/WARN]: [BetterChunkLoader] Invalid material: 96841
[01:09:52] [Server thread/WARN]: [BetterChunkLoader] Invalid material: 96842
```

**Comment by evernife** [comment]
I was retesting it... the minecraft names (CLAY;STONE) worked well, but you need to restart server for them to take effect (or use `/plugman reload BetterChunkLoader`

But the forge items do not work, i teste for exemple:

```
APPLIEDENERGISTICS2_TILE.BLOCKFLUIX  
CUSTOMTHINGS_BLOCK0:2    
THERMALFOUNDATION_STORAGE*5    
```

`/mt hand` respective names:

```
<appliedenergistics2:tile.BlockFluix>
<customthings:block0:2>
<ThermalFoundation:Storage:5>
```

So.. i think the problem is with non vanilla items T.T

**Comment by KaiKikuchi** [comment]
It works fine with most of modded blocks. You're specifying invalid IDs.

Do not use /mt hand for that, it won't show the bukkit material id.

Also the data/durability is not supported.

You can specify, for example, "CUSTOMTHINGS_BLOCK0", but it'll match all data ids. You cannot use "CUSTOMTHINGS_BLOCK0:2".

**Comment by evernife** [comment]
That kills me *_*

But ok, i will stay with IRON/Diamond blocks so... (until i create my own mod)
