### ISSUE TITLE
Changing dabase while online

### ISSUE THREAD

**Issue by evernife** [KaiKikuchi/BetterChunkLoader#14]
Ok. i know that this is really stupid and is really hard for someone to do... but.. i did ...

Change the database format while server is online kill the server.

I change from MySQL to XML, when i used `/betterchunkloader reload` the server stoped responding.

Here follows the log after i use the command :D [pastebin](http://pastebin.com/yWvZi1SY)

**Comment by KaiKikuchi** [comment]
Fixed on v.2.5
