### ISSUE TITLE
Add username table in the database 

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/BetterChunkLoader#16]
Would be nice add a username table in the database, following the UUID.

**Comment by KaiKikuchi** [comment]
This won't happen. Use another plugin for the uuid-name table, like [UUIDProvider](https://github.com/KaiKikuchi/UUIDProvider).

**Comment by Eufranio** [comment]
I would like to see the username in the db, only visually tho, would be a nice way to check and find chunk loaders when not in-game, but ok.
