### ISSUE TITLE
Give user max chunks if Chunk limit gets reached with a command

### ISSUE THREAD

**Issue by Rubbertjuh** [KaiKikuchi/BetterChunkLoader#17]
Having an issue when setting up donator packages, some users will already have 46 Chunks for example, but if 54 chunks is the max for online-only, and the command for buycraft for example is set to execute is: 
'bcl chunks add Rubbertjuh onlineonly 24 '

The plugin will just cancel the command and show us this message: 
https://gyazo.com/e9e43098768d23b81ba39cc1edb9c061
Would it be possible to show that message but still give the user the max allowed amount of chunks?

**Comment by KaiKikuchi** [comment]
Added in version 2.5.1

**Comment by evernife** [comment]
Was this really solved?

I was wondering that it should let the chunks for the player, but not pass the maximum in the config:

> Exemple:
> Max chunks is set to 50
> 
> Player has 45 chunks, he buys more 10 in the point shop, so, he should have 50...

**Comment by evernife** [comment]
UP

**Comment by KaiKikuchi** [comment]
Yes it is resolved.

Usage: /bcl chunks (add|set) (PlayerName) (alwayson|onlineonly) (amount) [max|force]";

If you specify "max" at the end of the command, it'll trim the amount to the maximum allowed amount. If you specify "force", it'll ignore the maximum allowed amount.

**Comment by evernife** [comment]
Thank you :D
