### ISSUE TITLE
Molecular Transformer loses energy connectors when chunk loader is reloaded (ie. I log in)

### ISSUE THREAD

**Issue by RaineAndrews** [KaiKikuchi/BetterChunkLoader#2]
As long as I'm with the molecular transformer, it works as intended.  But if the server restarts, or I log out before the item is finished, it gets stuck at 100% or the Immersive Engineering energy hubs break off.  I've read that other energy tubes also break with other chunk loaders, but not world anchors.

I'm using the current Infinity Evolved modpack on an expert mode server.  Any ideas what could be causing this?

**Comment by Mrmanishman** [comment]
Hey RaineAndrews.

Just a quick question which has nothing to do with your question, sorry.

Did you have any problems installing the plugin. A few other ppl seem to be having difficulties.

Any assistance would be appreciated.

Many thanks

Mrmanishman

**Comment by KaiKikuchi** [comment]
Unfortunately Github didn't send me any notification about a lot of issues, so I am sorry for the very late reply!

We have no issues with this plugin in our Infinity servers (all types).
