### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by MGKPartyBoy** [KaiKikuchi/BetterChunkLoader#26]
I have download Vault and installed it into my plugins.

I downloaded the BCLForgeLib (https://github.com/KaiKikuchi/BCLForgeLib): I extracted it and put it in my mod folder.

I downloaded the BCL plugin itself (https://github.com/KaiKikuchi/BetterChunkLoader): I extracted it and placed it in my plugins folder.

I read the how-to install, but IDK why the plugin isn't loading, working, or generating a config!

Running Minecraft Thermos 1.7.10 FTB.

**Comment by KaiKikuchi** [comment]
You have downloaded the source code instead of the latest jar release.

You have to download the latest release or compile the source code you have downloaded.

**Comment by MGKPartyBoy** [comment]
Where do I download the latest jar release? I searched everywhere, but I Could not find it!

**Comment by evernife** [comment]
![image](https://cloud.githubusercontent.com/assets/11357801/24826101/b6649992-1c04-11e7-8824-6a9f756868c8.png)

![image](https://cloud.githubusercontent.com/assets/11357801/24826108/d2b66008-1c04-11e7-805d-e70128a87510.png)
