### ISSUE TITLE
Unloaded entities ?

### ISSUE THREAD

**Issue by Worivee** [KaiKikuchi/BetterChunkLoader#27]
Hello,

On a moded server I have items that need to be dropped so that they get better, but the chunkloaders do not load them as soon as you leave the chunk or disconnect it (either with a chunkloader Online or offline chunkloader).

Is it normal ?

(items : seeds froms AE2)

**Comment by KaiKikuchi** [comment]
This chunk loader plugin, like common chunk loader mods, use the provided Forge Chunk Loader API, so if there is an issue with that you either have to ask the mod author and/or the Forge team. It's not related to this plugin nor any other chunk loader mod that use the Forge API to make chunk loaders.

Anyway, I think AE2 seeds grow normally with chunk loaders.
