### ISSUE TITLE
Update Suggestion: Add sharing chunks

### ISSUE THREAD

**Issue by Litleck** [KaiKikuchi/BetterChunkLoader#30]
Hello,

So on a server im playing that uses better chunk loaders is really annoying without sharing.  Im working with another person on the mod pack and I cant have the always online always online since on the server I play they make it stop loading below 12 tps.  Basically im suggesting that a way to share the chunks between two or more people be added so it'll load when either are on.

If this can be added ill appreciate it very much.

**Comment by KaiKikuchi** [comment]
This is unrelated to this project.
