### ISSUE TITLE
Usage Documentation?

### ISSUE THREAD

**Issue by WilliamLC98** [KaiKikuchi/BetterChunkLoader#5]
Title, I'm trying to set this up on my server, SkyFactory 2.4, with "cauldron-1.7.10-2.1403.1.54-server.jar" as my server jar, I downloaded both this and the BCLForgeLib file, and I've gotten as far as placing BetterChunkLoader-2.3.2.jar into the mods directory. Where is BCLForgeLib supposed to go, it's in the plugins directory atm, tried putting both into mods to no avail. On top of that, when I installed ItemRestrict, the config file it generated has options for BCL rather than ItemRestrict, which also has no usage documentation. This is all quite confusing, I'd appreciate if you or someone else who knows how to use these plugins could explain.

**Comment by Mrmanishman** [comment]
Hey WilliamLC98

Just a quicky, 

did you manage to get the plugin working? Wanting to get this plugin on my own server but dont want to run into any difficulties.

Kind regards

Mrmanishman

**Comment by WilliamLC98** [comment]
@Mrmanishman Unfortunately no, I had to remove it. It breaks plugin configs for some reason, overwriting their contents with it's own. It seems that if you want to be able to effectively manage chunk loading you'll want to use a mod pack with FTB Utilities. SkyFactory is just way too outdated and the work required to get it updated and working is way beyond my pay grade. I myself might end up simply switching to a newer mod pack.

**Comment by Mrmanishman** [comment]
I couldn't even get it to generate a config or affect anything. I've also struggled to get ftb utilities to work so ive ended up using chicken chunks to chunk load but I have had to dramatically change the config as a lot of people have problems. 

Just a shame this didn't work. Devco have this plugin and it works great for them. 

Can't have everything I suppose

Thanks for your reply

Mrsmanishman

**Comment by nini84** [comment]
you need to have library running with it to work properly

**Comment by Mrmanishman** [comment]
I did.

When I had the library, the server was noticing the plugin was there but was sending me so many errors which i couldn't find a fix for. I've removed it from my server because I just couldn't figure it out.

**Comment by Mrmanishman** [comment]
Hey nini84.

Where did you install the library file?

Thanks

Mrmanishman

**Comment by KaiKikuchi** [comment]
Unfortunately Github didn't send me any notification about a lot of issues, so I am sorry for the very late reply!

This plugin hasn't any interaction with ItemRestrict. Also I use ItemRestrict in about 50 servers and it hasn't any issue with BCL.

This plugin doesn't really need a documentation. Just add BCL and BCLForgeLib, add [permissions](https://github.com/KaiKikuchi/BetterChunkLoader/blob/master/src/main/resources/plugin.yml) to players and you're pretty good to go. Use the /bcl command to see all commands.
Anyway, I will add a README on this repository with requirements and installation info.

**Comment by evernife** [comment]
Just to know, BCLForgeLib goes into mods folder? or plugins folder?

**Comment by KaiKikuchi** [comment]
BCLForgeLib in mods folder (it's a forge mod), then BetterChunkLoader on the plugins folder.
