### ISSUE TITLE
permission.

### ISSUE THREAD

**Issue by Mrmanishman** [KaiKikuchi/BetterChunkLoader#7]
Hey kai

Loving your plugins. I am currently in process of setting up a server and your BetterChunkLoader would be a great plugin to use.

I know the plugin is available to download but I just want to make sure I have permission to use it.

Also, I have seen that a few people are having difficulty installing your plugin and not knowign where to install the BCL Lib file and I was just wondering if I do have permission, could you give me a quick message just to let me know how to install it.

Many thanks

Mrmanishman

P.S. I am in the process of building spawn and I have referenced yourself with some of the other plugins you have coded. 

Hope that is not a problem.

If you want to visit the server, by all means you are more than welcome

Infinity 2.4.2 server
manishcraft.nitrous.it

**Comment by KaiKikuchi** [comment]
Hello. Thank you for your support.

The BCLForgeLib goes on the mods folder. Of course, you need a Cauldron based server.

This plugin is open source and free to use under GPL v3 license.
