### ISSUE TITLE
Error's

### ISSUE THREAD

**Issue by Mrmanishman** [KaiKikuchi/BetterChunkLoader#8]
I have both the library and plugin installed.

Right clicking with the blaze rod works and the GUI appears where you can select what area you want chunkloaded. However, It does not actually chunk load and it spams the console with the attached errors.
[betterchunkloader.txt](https://github.com/KaiKikuchi/BetterChunkLoader/files/233649/betterchunkloader.txt)

**Comment by KaiKikuchi** [comment]
This is probably caused by an issue with the BCLForgeLib. Be sure to use a MC1.7.10 Cauldron based server (like Thermos). BCLForgeLib goes on the mods folder.
