### ISSUE TITLE
Breaking the Chunkloader Issue

### ISSUE THREAD

**Issue by lilmoefow** [KaiKikuchi/BetterChunkLoader#9]
When Breaking the BetterChunkloader using an pick axe that has an AOE such as the TerraShatterer from Botania, it will break the iron block but still leave the chunkloader active.  To remove I needed to delete the line from the .xml file.    

If I am breaking a block and the chunkloader gets caught in the aoe, the loader will still be active, even though the iron block gets broken.

**Comment by KaiKikuchi** [comment]
You can use "/bcl purge" instead. Unfortunately this cannot be fixed in any way, as it's the mod not invoking the appropriate event.

**Comment by lilmoefow** [comment]
I have just been going into the .xml file that saves all the chunkloaders and deleting the line manually.
